Timer graphics adjustments
LupoPasiniGames/CiarnuroTimer-Web pull request #16
Opened 2024-07-30 14:08 UTC by nicolasdellatorre

During a turn in the timer slide there is the player icon and "Turno" has become "Turno di gioco". How can I adjust the buttons?

2024-07-30 14:44 UTC, adolfintel commented
Can you explain the problem better? In italian is fine too

2024-07-30 15:35 UTC, nicolasdellatorre commented
Nella lista dei miglioramenti da fare c'è la voce "redesign della schermata del timer: sistemare l'ordine dei pulsanti". Cosa si intende? Grazie

2024-07-30 16:13 UTC, adolfintel commented
Era solo una cosa estetica e per chiarezza, aveva fatto una bozza Matteo, appena lo sento me la faccio dare

2024-08-01 14:01 UTC, nicolasdellatorre commented
Following Matteo's instructions: there is a differentiation between the name of the player and that of the character, the player's team is more clearer (even in the team timer) and the title attribute has been added to each button so that when passing over it with the mouse its function is clear.

2024-08-01 14:17 UTC, adolfintel requested changes
Looks good, Matteo just checked it too. I suggested a couple of improvements to the code.

2024-08-01 14:17 UTC, adolfintel commented on CiarnuroRT/webapp/ciarnurort.js
> +                I("playerAndCharacterName").innerHTML=e.player.playerName+"<br>"+"<span style='font-style:italic;'>"+e.player.characterName+"</span >";
Don't use br, use margin-top in CSS

2024-08-01 14:17 UTC, adolfintel commented on CiarnuroRT/webapp/index.html
> +                    <div style="text-align:center;font-size:1.4em;margin-bottom: 0.2em;" id="playerInfo"><img id="profilePic" style="position:relative;left:0.5em;border-radius:50%;height:4em;width:4e
Inline CSS should only be used for small variations of the style, move this style in the CSS file

2024-08-02 14:53 UTC, merged